In [1]:
import pandas as pd

In [2]:
inputDF = pd.read_csv('Train.csv')

In [5]:
col_temp = []
for i in inputDF.columns:
    col_temp.append(i.replace('.','_'))
inputDF.columns = col_temp

In [7]:
inputDF

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AT_PRESENT,BLOCK,LOT,BUILDING_CLASS_AT_PRESENT,ZIP_CODE,RESIDENTIAL_UNITS,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE
0,3,N36,01 ONE FAMILY DWELLINGS,1,8299,31,A5,82470,1,0,1,1650,1088,1942,1,A5,226000.0,2049-07-15
1,3,N81,10 COOPS ELEVATOR APARTMENTS,2,7579,29,D4,82444,0,0,0,0,0,1982,2,D4,173500.0,2049-07-08
2,4,N13,02 TWO FAMILY DWELLINGS,1,5945,52,B2,82594,2,0,2,3200,2359,2007,1,B2,1241000.0,2049-08-15
3,5,N103,02 TWO FAMILY DWELLINGS,1,5225,34,B2,81542,2,0,2,4315,2496,1997,1,B2,576000.0,2049-01-07
4,3,N20,02 TWO FAMILY DWELLINGS,1,6207,38,B2,82438,2,0,2,2500,2400,1962,1,B2,1489000.0,2049-09-17
5,5,N103,01 ONE FAMILY DWELLINGS,1,4579,46,A5,81542,1,0,1,2555,1536,2030,1,A5,251000.0,2049-09-18
6,5,N170,01 ONE FAMILY DWELLINGS,1,4657,100,A5,81540,1,0,1,2407,1400,2002,1,A5,536000.0,2049-08-01
7,4,N91,01 ONE FAMILY DWELLINGS,1,3210,40,A1,82609,1,0,1,2342,1350,1962,1,A1,756750.0,2048-11-20
8,4,N88,01 ONE FAMILY DWELLINGS,1,4849,49,A2,82588,1,0,1,3800,1105,1977,1,A2,889000.0,2049-09-22
9,2,N90,02 TWO FAMILY DWELLINGS,1,3286,49,B2,81692,2,0,2,3750,2136,1942,1,B2,551000.0,2048-10-29
10,3,N20,07 RENTALS WALKUP APARTMENTS,2A,6193,59,C3,82438,4,0,4,4000,3250,1961,2,C3,1551000.0,2049-06-20
11,3,N15,01 ONE FAMILY DWELLINGS,1,1596,27,A9,82455,1,0,1,2000,1400,1933,1,A9,731000.0,2049-09-23
12,4,N119,01 ONE FAMILY DWELLINGS,1,14002,120,A1,82648,1,0,1,4360,2160,1997,1,A1,736000.0,2048-12-30
13,3,N85,01 ONE FAMILY DWELLINGS,1,7843,3,A1,82468,1,0,1,2700,1152,1957,1,A1,551000.0,2049-06-05
14,4,N195,01 ONE FAMILY DWELLINGS,1,3416,38,A5,82619,1,0,1,1800,1260,1982,1,A5,796000.0,2049-05-02
15,3,N206,04 TAX CLASS 1 CONDOS,1A,7029,1002,R3,82458,1,0,1,0,0,2035,1,R3,531000.0,2049-01-07
16,4,N138,29 COMMERCIAL GARAGES,4,349,5,G2,82340,0,1,1,2850,1188,1962,4,G2,4101000.0,2048-11-12
17,5,N241,01 ONE FAMILY DWELLINGS,1,485,21,A5,81548,1,0,1,2000,1300,2034,1,A5,501000.0,2049-09-10
18,3,N83,03 THREE FAMILY DWELLINGS,1,4716,66,C0,82446,3,0,3,2600,2560,1992,1,C0,401000.0,2049-10-02
19,4,N200,01 ONE FAMILY DWELLINGS,1,13491,18,A2,82647,1,0,1,4850,920,1962,1,A2,861000.0,2049-10-08
20,5,N165,02 TWO FAMILY DWELLINGS,1,4229,316,B9,81540,2,0,2,1214,1120,2029,1,B9,566000.0,2049-10-03
21,3,N23,13 CONDOS ELEVATOR APARTMENTS,2,185,1213,R4,82451,1,0,1,0,0,2048,2,R4,127750.0,2049-05-09
22,4,N89,01 ONE FAMILY DWELLINGS,1,6605,33,A5,82601,1,0,1,2500,1332,1967,1,A5,751000.0,2049-07-16
23,2,N211,02 TWO FAMILY DWELLINGS,1,3497,10,B3,81707,2,0,2,5000,3110,1962,1,B3,500999.0,2049-09-24
24,3,N36,02 TWO FAMILY DWELLINGS,1,8016,49,B1,82470,2,0,2,2200,2024,1992,1,B1,471000.0,2049-04-01
25,3,N85,03 THREE FAMILY DWELLINGS,1,7847,37,C0,82468,3,0,3,2667,2409,1952,1,C0,836000.0,2049-09-11
26,1,N112,22 STORE BUILDINGS,4,2068,43,K2,81266,0,1,1,2500,4200,1958,4,K2,1501000.0,2049-08-21
27,3,N83,13 CONDOS ELEVATOR APARTMENTS,2,4815,1021,R4,82437,1,0,1,0,0,2046,2,R4,467440.0,2049-05-08
28,5,N5,14 RENTALS 410 UNIT,2A,3098,27,S3,81539,3,1,4,14145,7300,1992,2,S3,1801000.0,2049-07-07
29,3,N69,02 TWO FAMILY DWELLINGS,1,4299,11,B3,82441,2,0,2,1900,1560,1957,1,B3,469000.0,2049-03-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29970,3,N80,01 ONE FAMILY DWELLINGS,1,5101,24,A9,82460,1,0,1,2475,2544,1962,1,A9,1371000.0,2048-11-15
29971,3,N80,04 TAX CLASS 1 CONDOS,1A,5107,1022,R3,82460,1,0,1,0,0,2020,1,R3,360000.0,2049-02-26
29972,2,N196,10 COOPS ELEVATOR APARTMENTS,2,5953,545,D4,81705,0,0,0,0,0,1986,2,D4,86000.0,2049-02-19
29973,3,N245,02 TWO FAMILY DWELLINGS,1,2788,4,S2,82440,2,1,3,2500,5000,1952,1,S2,2526000.0,2049-05-14
29974,4,N218,01 ONE FAMILY DWELLINGS,1,12636,26,A5,82645,1,0,1,3237,1440,1972,1,A5,433000.0,2048-12-13
29975,4,N146,02 TWO FAMILY DWELLINGS,1,2715,21,B1,82612,2,0,2,2500,1656,1992,1,B1,701000.0,2049-02-19
29976,3,N177,09 COOPS WALKUP APARTMENTS,2C,962,14,C6,82449,0,0,0,0,0,1952,2,C6,1201000.0,2049-09-02
29977,3,N206,03 THREE FAMILY DWELLINGS,1,7024,110,C0,82458,3,0,3,6800,2391,1962,1,C0,791000.0,2049-04-21
29978,4,N218,01 ONE FAMILY DWELLINGS,1,11011,3,A1,82646,1,0,1,3000,936,1962,1,A1,495000.0,2048-11-07
29979,3,N102,13 CONDOS ELEVATOR APARTMENTS,2,6381,1004,R4,82448,1,0,1,0,0,1988,2,R4,416740.0,2049-02-11
29980,4,N138,27 FACTORIES,4,367,8,F5,82335,0,1,1,7900,7900,1980,4,F5,8001000.0,2049-01-28
29981,3,N247,13 CONDOS ELEVATOR APARTMENTS,2,2135,1982,R4,82483,1,0,1,0,0,2041,2,R4,6609442.0,2048-11-14
29982,3,N36,02 TWO FAMILY DWELLINGS,1,8173,12,B2,82470,2,0,2,1600,1760,2037,1,B2,595000.0,2049-05-01
29983,4,N148,01 ONE FAMILY DWELLINGS,1,2979,116,A5,82613,1,0,1,1844,1224,1972,1,A5,701400.0,2049-04-03
29984,5,N252,01 ONE FAMILY DWELLINGS,1,7105,587,A5,81543,1,0,1,2464,1860,2043,1,A5,591000.0,2049-07-16
29985,5,N143,01 ONE FAMILY DWELLINGS,1,689,220,A1,81548,1,0,1,12750,2477,2012,1,A1,816000.0,2049-05-26
29986,5,N32,01 ONE FAMILY DWELLINGS,1,1659,122,A5,81548,1,0,1,1428,1321,2026,1,A5,427000.0,2049-09-16
29987,3,N15,46 CONDO STORE BUILDINGS,4,1754,1001,RK,82440,0,0,1,0,0,2039,4,RK,52351000.0,2048-10-31
29988,5,N51,01 ONE FAMILY DWELLINGS,1,649,6,A1,81538,1,0,1,2500,2042,2047,1,A1,458000.0,2048-12-23
29989,2,N14,02 TWO FAMILY DWELLINGS,1,3331,52,B3,81701,2,0,2,3000,1801,1947,1,B3,305200.0,2049-02-06
29990,3,N102,02 TWO FAMILY DWELLINGS,1,6471,69,B3,82448,2,0,2,2287,1816,1937,1,B3,901000.0,2049-04-03
29991,3,N153,10 COOPS ELEVATOR APARTMENTS,2,6709,1,D4,82464,0,0,0,0,0,1973,2,D4,431000.0,2048-12-19
29992,2,N14,09 COOPS WALKUP APARTMENTS,2,3347,43,C6,81701,0,0,0,0,0,1956,2,C6,65250.0,2049-05-12
29993,3,N144,01 ONE FAMILY DWELLINGS,1,8824,15,A2,82463,1,0,1,7000,1850,1992,1,A2,841000.0,2049-07-16
29994,2,N131,01 ONE FAMILY DWELLINGS,1,3199,14,A9,81702,1,0,1,1353,1710,1933,1,A9,351000.0,2049-02-12
29995,4,N8,03 THREE FAMILY DWELLINGS,1,843,5,C0,82339,3,0,3,2500,3300,1997,1,C0,1601000.0,2049-02-26
29996,4,N124,01 ONE FAMILY DWELLINGS,1,9828,36,A1,82666,1,0,1,2000,1280,1952,1,A1,462000.0,2049-10-21
29997,5,N145,02 TWO FAMILY DWELLINGS,1,1246,37,B2,81537,2,0,2,2943,1800,2035,1,B2,293000.0,2049-08-05
29998,4,N214,01 ONE FAMILY DWELLINGS,1,11816,12,A1,82654,1,0,1,2000,840,1933,1,A1,491000.0,2049-02-05
29999,5,N74,01 ONE FAMILY DWELLINGS,1,5653,124,A5,81546,1,0,1,1208,1480,2021,1,A5,382097.0,2049-05-02